export const DATA_LOADING = 'DATA_LOADING';
export const DATA_SUCCESS = 'DATA_SUCCESS';
export const DATA_ERR = 'DATA_ERR';
export const PUSH_ELEM_TO_CATEGORY = 'PUSH_ELEM_TO_CATEGORY';
export const SUCC_DELETE = 'SUCC_DELETE';
export const ERR_ADD_CATEGORY = 'ERR_ADD_CATEGORY';
export const CATEGORY_SUCC_EDIT = 'CATEGORY_SUCC_EDIT';


//subcategories types
export const SUBCATEGORY_SUCC_LOAD = 'SUBCATEGORY_SUCC_LOAD';
export const SUBCATEGORY_ERROR_LOAD = 'SUBCATEGORY_ERROR_LOAD';
export const SUBCATEGORY_SUCC_ADD = 'SUBCATEGORY_SUCC_ADD';
export const SUBCATEGORY_ERROR_ADD = 'SUBCATEGORY_ERROR_ADD'; 
export const SUBCATEGORY_ADD_ELEM = 'SUBCATEGORY_ADD_ELEM';
export const SUBCATEGORY_SUCC_EDIT = 'SUBCATEGORY_SUCC_EDIT';


export const GOODS_SUCC_LOAD = 'GOODS_SUCC_LOAD';
export const GOODS_ERROR_LOAD = 'GOODS_ERROR_LOAD';
export const GOODS_SUCC_ADD = 'GOODS_SUCC_ADD';
export const GOODS_ERROR_ADD = 'GOODS_ERROR_ADD'; 
export const GOODS_ADD_ELEM = 'GOODS_ADD_ELEM';
export const GOODS_DEL_ELEM = 'GOODS_DEL_ELEM';



export default null;
